# Code 2.7.1: Broadcasting a row and a column

Adds a vector of shape `(3,)` and a column of shape `(2, 1)` to a `(2, 3)` matrix; the results are shown in the comments.


In [ ]:
import numpy as np

A = np.arange(6.0).reshape(2, 3)     # shape (2, 3)
b = np.array([10.0, 20.0, 30.0])     # shape (3,)
print(A + b)                         # b is added to each row
# [[10. 21. 32.]
#  [13. 24. 35.]]
col = np.array([[100.0], [200.0]])   # shape (2, 1)
print(A + col)                       # col is added to each column
# [[100. 101. 102.]
#  [203. 204. 205.]]
